version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "composer"
    directory: /
    schedule:
      interval: "monthly"
    groups:
      composer-minor:
        update-types:
          - "minor"
          - "patch"
