---

services:

  redis-official:
    image: ${REDIS_IMAGE_NAME:-redis:7.4}
    container_name: redis-standalone
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"
    profiles:
      - all
      - official
      - standalone

  redis-clients:
    image: ${REDIS_IMAGE_NAME:-redislabs/client-libs-test:7.4.2}
    container_name: redis-standalone
    environment:
      - TLS_ENABLED=yes
      - REDIS_CLUSTER=no
      - PORT=6379
      - TLS_PORT=6666
    command: ${REDIS_EXTRA_ARGS:---enable-debug-command yes --enable-module-command yes --tls-auth-clients optional --save ""}
    ports:
      - 6379:6379
      - 6666:6666 # TLS port
    volumes:
      - "./dockers/standalone:/redis/work"
    profiles:
      - all
      - clients
      - standalone

  redis-cluster:
    image: ${REDIS_IMAGE_NAME:-redislabs/client-libs-test:7.4.2}
    container_name: redis-cluster
    environment:
      - REDIS_CLUSTER=yes
      - NODES=6
      - REPLICAS=1
      - TLS_ENABLED=yes
      - PORT=16379
      - TLS_PORT=27379
    command: ${REDIS_EXTRA_ARGS:---enable-debug-command yes --enable-module-command yes --tls-auth-clients optional --save ""}
    ports:
      - "6372-6377:16379-16384"
    volumes:
      - "./dockers/cluster:/redis/work"
    profiles:
      - all
      - clients
      - cluster

  redis-stack:
    image: ${REDIS_STACK_IMAGE_NAME:-redislabs/client-libs-test:rs-7.4.0-v2}
    container_name: redis-stack
    ports:
      - "6479:6379"
    environment:
      - REDIS_CLUSTER=no
      - PORT=6379
    command: ${REDIS_EXTRA_ARGS:---enable-debug-command yes --enable-module-command yes --save ""}
    volumes:
      - "./dockers/redis-stack:/redis/work"
    profiles:
      - all
      - clients
      - stack
