version: "3.9"
services:
  cluster:
    container_name: redis-cluster
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6372:6372"
      - "6373:6373"
      - "6374:6374"
      - "6375:6375"
      - "6376:6376"
      - "6377:6378"
    volumes:
      - "./redis.conf:/redis.conf:ro"

